global using System;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Documents;
global using System.Windows.Input;
//obal using DB.Inventory.Models;
global using System.Windows.Media;
global using CI.Standard.Lib.Helpers;
global using CI.Visual.Lib.Extensions;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using StandardContracts.Lib;
global using static System.Diagnostics.Trace;
global using static System.Media.SystemSounds;